# Generated by Django 3.2.4 on 2021-06-27 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boozerstoryapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ComentModel',
            new_name='CommentModel',
        ),
        migrations.RenameField(
            model_name='commentmodel',
            old_name='coment',
            new_name='comment',
        ),
    ]
